export const currencyPairs = [
  { code: 'EURUSD', label: '🇪🇺/🇺🇸 EUR/USD' },
  { code: 'AUDUSD', label: '🇦🇺/🇺🇸 AUD/USD' },
  { code: 'EURJPY', label: '🇪🇺/🇯🇵 EUR/JPY' },
  { code: 'GBPJPY', label: '🇬🇧/🇯🇵 GBP/JPY' },
  { code: 'GBPAUD', label: '🇬🇧/🇦🇺 GBP/AUD' },
  { code: 'USDCAD', label: '🇺🇸/🇨🇦 USD/CAD' },
  { code: 'USDCHF', label: '🇺🇸/🇨🇭 USD/CHF' },
  { code: 'GBPCHF', label: '🇬🇧/🇨🇭 GBP/CHF' },
  { code: 'USDJPY', label: '🇺🇸/🇯🇵 USD/JPY' },
  { code: 'AUDCAD', label: '🇦🇺/🇨🇦 AUD/CAD' },
  { code: 'AUDCHF', label: '🇦🇺/🇨🇭 AUD/CHF' },
  { code: 'AUDJPY', label: '🇦🇺/🇯🇵 AUD/JPY' },
  { code: 'CADJPY', label: '🇨🇦/🇯🇵 CAD/JPY' },
  { code: 'CHFJPY', label: '🇨🇭/🇯🇵 CHF/JPY' },
  { code: 'EURAUD', label: '🇪🇺/🇦🇺 EUR/AUD' },
  { code: 'EURCAD', label: '🇪🇺/🇨🇦 EUR/CAD' },
  { code: 'EURCHF', label: '🇪🇺/🇨🇭 EUR/CHF' },
  { code: 'EURGBP', label: '🇪🇺/🇬🇧 EUR/GBP' },
  { code: 'GBPCAD', label: '🇬🇧/🇨🇦 GBP/CAD' },
  { code: 'GBPUSD', label: '🇬🇧/🇺🇸 GBP/USD' },
];

// src/data/otcData.ts

export const otcPairs = {
  forex: [
    '🇳🇿/🇨🇦 NZD/CAD',
    '🇨🇦/🇨🇭 CAD/CHF',
    '🇦🇺/🇨🇦 AUD/CAD',
    '🇦🇺/🇨🇭 AUD/CHF',
    '🇪🇺/🇯🇵 EUR/JPY',
    '🇬🇧/🇺🇸 GBP/USD',
    '🇺🇸/🇩🇿 USD/DZD',
    '🇬🇧/🇳🇿 GBP/NZD',
    '🇺🇸/🇨🇭 USD/CHF',
    '🇺🇸/🇨🇴 USD/COP',
    '🇺🇸/🇮🇩 USD/IDR',
    '🇪🇺/🇨🇭 EUR/CHF',
    '🇦🇺/🇺🇸 AUD/USD',
    '🇺🇸/🇧🇷 USD/BRL',
    '🇪🇺/🇨🇦 EUR/CAD',
    '🇬🇧/🇯🇵 GBP/JPY',
    '🇬🇧/🇨🇦 GBP/CAD',
    '🇦🇺/🇯🇵 AUD/JPY',
    '🇨🇭/🇯🇵 CHF/JPY',
    '🇪🇺/🇺🇸 EUR/USD',
    '🇬🇧/🇦🇺 GBP/AUD',
    '🇳🇿/🇨🇭 NZD/CHF',
    '🇳🇿/🇯🇵 NZD/JPY',
    '🇺🇸/🇨🇦 USD/CAD',
    '🇺🇸/🇯🇵 USD/JPY',
    '🇺🇸/🇳🇬 USD/NGN',
    '🇪🇺/🇦🇺 EUR/AUD',
    '🇺🇸/🇲🇽 USD/MXN',
    '🇺🇸/🇦🇷 USD/ARS',
    '🇺🇸/🇧🇩 USD/BDT',
    '🇺🇸/🇮🇳 USD/INR',
    '🇺🇸/🇵🇰 USD/PKR',
    '🇪🇺/🇳🇿 EUR/NZD',
    '🇪🇺/🇸🇬 EUR/SGD',
  ],
  crypto: [
    'Ethereum (OTC)',
    'Litecoin (OTC)',
    'Solana (OTC)',
    'Toncoin (OTC)',
    'TRON (OTC)',
    'Ripple (OTC)',
    'Bitcoin (OTC)',
    'Binance Coin (OTC)',
  ],
};